#trigger:
#- main

pool: D65

variables:
  COMPONENT: frontend


resources:
  repositories:
    - repository: templates
      type: github
      name: raghudevopsb65/roboshop-azure-devops-templates
      endpoint: raghudevopsb65

stages:
- template: nginx.yml@templates

